package datastructure.homework7

fun main(args: Array<String>) {

    val nameStudentTree = TreeNode("Name students tree.")
    val boyName = TreeNode("Boy name")
    val girlName = TreeNode("Girl name")
    nameStudentTree.addChild(boyName)
    nameStudentTree.addChild(girlName)
    val nameABoy = TreeNode("Name A boy ")
    boyName.addChild(nameABoy)
    val nameAGirl = TreeNode("Name A girl ")
    girlName.addChild(nameAGirl)
    val nameBBoy = TreeNode("Name B boy ")
    boyName.addChild(nameBBoy)
    val nameBGirl = TreeNode("Name B girl ")
    girlName.addChild(nameBGirl)
    val nameCBoy = TreeNode("Name C boy ")
    boyName.addChild(nameCBoy)
    val nameCGirl = TreeNode("Name C girl ")
    girlName.addChild(nameCGirl)
    val nameDBoy = TreeNode("Name D boy ")
    boyName.addChild(nameDBoy)
    val nameDGirl = TreeNode("Name D girl ")
    girlName.addChild(nameDGirl)
    val nameFBoy = TreeNode("Name F boy ")
    boyName.addChild(nameFBoy)
    val nameFGirl = TreeNode("Name F girl ")
    girlName.addChild(nameFGirl)
    val aziz = TreeNode("Aziz")
    val azim = TreeNode("Azim")
    val azamat = TreeNode("Azamat")
    nameABoy.addChild(aziz)
    nameABoy.addChild(azim)
    nameABoy.addChild(azamat)
    val aziza = TreeNode("Aziza")
    val anora = TreeNode("Anora")
    val afruza = TreeNode("Afruza")
    nameAGirl.addChild(aziza)
    nameAGirl.addChild(anora)
    nameAGirl.addChild(afruza)
    val bekzod = TreeNode("Bekzod")
    val behruz = TreeNode("Bexruz")
    nameBBoy.addChild(behruz)
    nameBBoy.addChild(bekzod)
    val baxoroyim = TreeNode("Baxoroyim")
    val barno = TreeNode("Barno")
    nameBGirl.addChild(barno)
    nameBGirl.addChild(baxoroyim)
    val sardor = TreeNode("Sardor")
    val sanjar = TreeNode("Sanjar")
    nameCBoy.addChild(sanjar)
    nameCBoy.addChild(sardor)
    val sarvinoz = TreeNode("Sarvinoz")
    val sabina = TreeNode("Sabina")
    nameCGirl.addChild(sabina)
    nameCGirl.addChild(sarvinoz)
    val davron = TreeNode("Davron")
    val dilmurod = TreeNode("Dilmurod")
    nameDBoy.addChild(davron)
    nameDBoy.addChild(dilmurod)
    val dilafruz = TreeNode("Dilafruz")
    val dilnoza = TreeNode("Dilnoza")
    nameDGirl.addChild(dilafruz)
    nameDGirl.addChild(dilnoza)
    val firdavs = TreeNode("Firdavs")
    val feruz = TreeNode("Feruz")
    val faxriddin = TreeNode("Faxriddin")
    nameFBoy.addChild(firdavs)
    nameFBoy.addChild(feruz)
    nameFBoy.addChild(faxriddin)

    val farangiz = TreeNode("Farangiz")
    val feruza = TreeNode("Feruza")
    val farzona = TreeNode("Farzona")
    nameFGirl.addChild(farangiz)
    nameFGirl.addChild(feruza)
    nameFGirl.addChild(farzona)
    println("Bu bizning talabalar ismidan tuzilgan daraxtimiz.....")
    println(nameStudentTree)


}